export * from './model/type'
export * from './api/getProducto.ts'
export * from './api/getProductos.ts'
export * from './api/getLotesProduccion.ts'
export * from './hooks/useProducto'
export * from './hooks/useProductos'
export * from './hooks/useLotesProductos.ts'
export * from './lib/formatProducto.ts'
export * from './ui/ProductoCard.tsx'
export {default as ProductoForm} from './ui/ProductoForm.tsx'
//export * from './hooks/useEmpleados'
//export * from './ui/EmployeeAvatar'
