export * from './model/type.ts'
export * from './api/ClienteApi.ts'
export * from './hooks/useClientes.ts'
export * from './lib/formatClienteNombre.ts'
export * from './ui/ClienteCard.tsx'
//export * from './hooks/useEmpleados'
//export * from './ui/EmployeeAvatar'
